version: '2'
services:
    nginx:
        image: nginx:alpine
        container_name: payme-back-nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html/
            - ./.devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        tty: true
        links:
            - php
        networks:
            - payme-back
    php:
        container_name: payme-back-php
        image: php:7.4-fpm-alpine
        user: "${uid}:${gid}"
        build: ./.devops/fpm
        environment:
            APP_NAME: payme-back
            APP_ENV: local
            APP_KEY: base64:rZkvdPk8OVsPQm//v1wiTnoomHPyqBwEFtj2AsuwHHM=
            APP_DEBUG: "true"
            APP_URL: http://payme-back.local
            PSYSH_CONFIG: /var/www/html/.devops/psysh/config.php
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: payme
            DB_USERNAME: payme
            DB_PASSWORD: 12345

        volumes:
            - .:/var/www/html/
            - ./.devops/fpm/php.ini:/usr/local/etc/php/php.ini
            - ./.devops/psysh:/var/www/html/.devops/psysh
        links:
            - postgres
        networks:
            - payme-back

    postgres:
        image: postgres
        container_name: payme-back-postgres
        ports:
            - "15432:5432"
        volumes:
            - payme-back-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: payme
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: payme
        networks:
            - payme-back

networks:
    payme-back:
        driver: bridge

volumes:
    payme-back-postgres:
        driver: local
