<?php

namespace Tests\Unit\Services;

use App\Services\CountryService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CountryServiceTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var CountryService
     */
    private $countryService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->countryService = new CountryService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testSuccessCreate()
    {
        $this->countryService->create();

        $this->assertTrue(true);
    }
}
